### ISSUE TITLE
CosmosContractNegotiationStoreIntegrationTests failing in CI

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/DataSpaceConnector#255]
# Bug Report

Upstream issue TBD

## Describe the Bug

Azure Cosmos DB integration tests are failing in CI on main branch in EDC repo: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/workflows/verify.yaml?query=branch:main

### Observed Behavior

findAll_verifySortingInvalidSortField and queryAgreements_verifySorting_invalidProperty tests from CosmosContractNegotiationStoreIntegrationTest suite are failing with a stacktrace:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6228775974?check_suite_focus=true

```
CosmosContractNegotiationStoreIntegrationTest > findAll_verifySortingInvalidSortField() FAILED
    java.lang.AssertionError: 
    Expecting empty but was: [org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@887a63a7,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@204c288,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@57b86ed7,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@b767b2f9,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@d1b3572c,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@64531efb,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@c3ea4f43,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@b4ef69c,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@47a0706,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.negotiation.ContractNegotiation@c2209141]
        at org.eclipse.dataspaceconnector.contract.negotiation.store.CosmosContractNegotiationStoreIntegrationTest.findAll_verifySortingInvalidSortField(CosmosContractNegotiationStoreIntegrationTest.java:450)

CosmosContractNegotiationStoreIntegrationTest > queryAgreements_verifySorting_invalidProperty() FAILED
    java.lang.AssertionError: 
    Expecting empty but was: [org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@b91ca37d,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@2707ff31,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@1d55b6df,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@79342336,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@2fb80672,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@734ad9b5,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@6337d27a,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@8dc155c0,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@e98cc089,
        org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@37534536]
        at org.eclipse.dataspaceconnector.contract.negotiation.store.CosmosContractNegotiationStoreIntegrationTest.queryAgreements_verifySorting_invalidProperty(CosmosContractNegotiationStoreIntegrationTest.java:541)

```

## Steps to Reproduce

See logs in [Azure-CosmosDB-Integration-Tests](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6228775974?check_suite_focus=true#logs) Github action for runs executed on main after PR merge.

## Possible Implementation

Possible cause is that the database is not cleaned up before the tests are run and the database contains some data from previous runs.

Possible fix: clean up the database before the test.

### Tasks
- [ ] create upstream issue
- [ ] clean the test data before/after the CosmosDb int tests

**Comment by chrislomonico** [comment]
Needs to be linked to upstream issue when the issue is ready; @cpeeyush can you follow-up with Paul on this one

**Comment by zeier** [comment]
Will be tracked in upstream issue https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1286
